

before_script:
  # Update packages 
  - apt-get update -yqq

  # Install Composer and project dependencies.
  - curl -sS https://getcomposer.org/installer
  - php composer.phar install 

   # Create a New Laravel App
  - composer create-project --prefer-dist laravel/laravel test-app
  # CD into the new laravel app
  - cd test-app
  # Include Multiauth Package
  - composer require bitfumes/laravel-multiauth
  - php artisan make:auth

  # Remove the default phpunit.xml and replace it with ultiauth phpunit.xml
  - rm phpunit.xml
  - rm -R tests
  - cp vendor/bitfumes/laravel-multiauth/testUnit.xml phpunit.xml
  - cp -R vendor/bitfumes/laravel-multiauth/tests tests

test:
  script:
  - php vendor/bin/phpunit