language: php

php:
  - 7.1

before_script:
   # Create a New Laravel App
  - composer create-project --prefer-dist laravel/laravel test-app
  # CD into the new laravel app
  - cd test-app
  # Include Multiauth Package
  - composer require bitfumes/laravel-multiauth

  # Remove the default phpunit.xml and replace it with chatter phpunit.xml
  - rm phpunit.xml
  - rm -R tests
  - cp vendor/bitfumes/laravel-multiauth/phpunit.xml phpunit.xml
  - cp -R vendor/bitfumes/laravel-multiauth/tests tests

script:
  - vendor/bin/phpunit